### ISSUE TITLE
Original Save and Restore dialogs are not translated

### ISSUE THREAD

**Issue by OmerMor** [adventurebrew/HebrewAdventure#2]
And also the Hebrew in the save titles is reversed:
![scummvm-sq3-he-00000](https://user-images.githubusercontent.com/95082/97190243-26f0dd80-17ae-11eb-9652-dd6a2e66aac6.png)

You have to enable the following option to see these dialogs:
![image](https://user-images.githubusercontent.com/95082/97190541-8222d000-17ae-11eb-998c-b46458e263d0.png)

**Comment by ZvikaZ** [comment]
That's a nice one!
Didn't even think that it's working...

OK, I will check it.

**Comment by ZvikaZ** [comment]
So, we have few issues here:
1. The game list isn't proper BiDi
2. The dialog text isn't translated.
3. The dialog is drawn like an English dialog.

Issue 1 is fixed at https://github.com/scummvm/scummvm/pull/2570
I assume it will take time to be accepted, so you might want to take the PR.

Issue 3 should be fixed in the game scripts, I will fix it together with 2.

**Comment by ZvikaZ** [comment]
The new release (https://github.com/ZvikaZ/HebrewAdventure/releases/tag/sq3_hebrew_2) has improved issue 3.
However, there's still some missing translation, and I haven't touched issue 3 yet.
Also, now there's a new warning.

So, still keeping this open.

To summarize, we still have:

2. Few more translation needed
3. The dialog is drawn like an English dialog.
4. Debug the warning.

**Comment by ZvikaZ** [comment]
I've looked at the warning. It's there also in the original English SQ3.
Therefore, it's out of scope for this issue...

**Comment by ZvikaZ** [comment]
@OmerMor , 
I have nothing really to update, but I'd wanted you to notice that the repo was relocated.
Note the new URL

**Comment by ZvikaZ** [comment]
Fixed at last :-)

Take https://github.com/adventurebrew/HebrewAdventure/files/5825243/PATCHES.zip
And https://github.com/scummvm/scummvm/pull/2735

Thanks for reporting.

**Comment by ZvikaZ** [comment]
The PR was merged, closing.
