### ISSUE TITLE
Save games with Hebrew title are garbled in ScummVM

### ISSUE THREAD

**Issue by OmerMor** [adventurebrew/HebrewAdventure#3]
When saving a game through the original save screen, it is possible to name it in Hebrew.
When doing so, ScummVM is unable to show the title correctly in its native load screen:
![scummvm-sq3-he-00003](https://user-images.githubusercontent.com/95082/97217839-84962180-17d0-11eb-9863-10048d4a0c32.png)

**Comment by ZvikaZ** [comment]
The garbling is fixed at https://github.com/scummvm/scummvm/pull/2571
However, now that we can read the text, we see that it's mirrored...

That's a matter for another PR.

**Comment by ZvikaZ** [comment]
If ScummVM's GUI language is Hebrew, the save game's text isn't mirrored.
So, it's probably a bug in ScummVM's GUI BiDi - it calls BiDI algorithm only if the GUI language is RTL (assuming that if the GUI language is English, for example, there won't be any RTL text...)

EDIT
----
Fixed at https://github.com/scummvm/scummvm/pull/2572

**Comment by ZvikaZ** [comment]
The second PR was merged.
Closing.
Thanks for the reports!
