### ISSUE TITLE
The tail in Fester Blatz's speech balloon is detached from the text box

### ISSUE THREAD

**Issue by OmerMor** [adventurebrew/HebrewAdventure#4]
Compare the speech balloon tails in the English vs. the Hebrew version:

![scummvm-sq3st-00001](https://user-images.githubusercontent.com/95082/97227535-4e5f9e80-17de-11eb-9bfc-3f19a8eae75e.png)

![scummvm-sq3-he-00005](https://user-images.githubusercontent.com/95082/97227561-561f4300-17de-11eb-9226-14e463e87982.png)

To repro, start the game, open the debugger (CTRL-ALT-D), and type `room 470`.

**Comment by ZvikaZ** [comment]
Fixed at https://github.com/adventurebrew/HebrewAdventure/releases/tag/sq3_hebrew_4
