### ISSUE TITLE
Total order price in Monolith Burger is misaligned in cashier's speech bubble

### ISSUE THREAD

**Issue by OmerMor** [adventurebrew/HebrewAdventure#6]
See here:
![scummvm-sq3-he-00010](https://user-images.githubusercontent.com/95082/99778604-92fc0280-2b1c-11eb-9167-aa8a211e9b55.png)

Savegame in Monolith Burger can be found here:
[sq3-he.zip](https://github.com/ZvikaZ/HebrewAdventure/files/5572289/sq3-he.zip)

To reproduce:

1. Stand in front of the cashier.
2. Type "הזמן".
3. Press "7" to order the fun meal.
4. Press "צ" to exit the menu.
5. Press "כן" multiple times to answer the cashier's questions.

The cashier will give you your total. However the number is misaligned in the speech bubble.

**Comment by ZvikaZ** [comment]
Fixed at https://github.com/adventurebrew/HebrewAdventure/releases/tag/sq3_hebrew_4

**Comment by ZvikaZ** [comment]
Thanks for your reports!
