### ISSUE TITLE
RTL not working properly.

### ISSUE THREAD

**Issue by Acemcjack** [adventurebrew/HebrewAdventure#8]
![Screenshot 2020-12-23 10 51 21](https://user-images.githubusercontent.com/76515231/102979334-99600e80-450e-11eb-8788-355286604340.png)
ScummVM version - 2.2.1
SQ3 version - GOG.com

Help!

**Comment by Acemcjack** [comment]
Solved!
I downloaded another version of ScummVM and it works now.

**Comment by ZvikaZ** [comment]
Glad to help ;-)
